### ISSUE TITLE
Skills with prefab SVGs don't show in dropdown 

### ISSUE THREAD

**Issue by abhinavc** [adamarla/qQuill#18]
This is gating issue !! 

All LaTeX eventually boils down to SVG. But if the SVG is provided directly, then Quill treats it differently. 
Try providing a SVG as the study note for a skill. It wouldn't show when the skill is selected to be set.

**Comment by adamarla** [comment]
This issue is fixed for prefab svgs in the study note. There is still a problem for pre fab svg in the skill statement, I think not having prefab svgs for the skill statement is a safe assumption for now till that part is fixed.

**Comment by abhinavc** [comment]
No ... The skill's statement could also be a prefab SVG. 

But then, it shouldn't make a difference. Somewhere in quill's flow, the LaTeX must be getting converted to SVG and the SVG then rendered to be shown. Everything should work the same way.

**Comment by abhinavc** [comment]
Yes, I do get notifications

**Comment by adamarla** [comment]
The only place where the an svg does not display properly is in the drop down (combo box) for skill statements which is due to some kind of dynamic sizing issue. The process followed to display svgs is the same as when rendering a skill study note which does display properly.

Straight LaTeX typed into quill is displayed as an image directly using JLatexMath. It does not get converted to svg till quill -r is run on the server.

**Comment by abhinavc** [comment]
There is also something amiss with the svgs generated by quill -r. There is
no viewBox in the svg. SVGs generated by other means have it and hence - as
long as they are within a certain width - nothing much needs to be done to
render them on the phone. Can't say the same for SVG s generated by quill

**Comment by adamarla** [comment]
It might be a related problem. I'm looking into it.

**Comment by adamarla** [comment]
Pushed an update which includes the viewBox attribute at the root node of SVGs.

Rendering Skill statement preview as element of combobox item still remains.

**Comment by abhinavc** [comment]
Need this issue to be resolved. Can't tag without it. 

Also, the skill SVGs are rendered really small. 
The newer SVGs for skills are rendered against a baseline width of 480px. 

The resizing logic in the app is therefore as follows

   `targetW = svgW / 480 ;`
    `targetH = targetW / aspectRatio`

Something similar would need to be done in Quill also.

**Comment by adamarla** [comment]
This is fixed. But I had to pull in a new jar to transcode svg to buffered image. Therefore you will need to perform a quill -d to download the new library.

There will also be a regular delta upgrade (quill -u) shortly because I need to rationalize the code a little bit due to the library change. But that should not effect the functionality in any way.

**Comment by adamarla** [comment]
Fixed as part of commit d0c39a1dcba68753f3985b2964f9a7d97353bdb9
