### ISSUE TITLE
Remove SAX check on allowed attributes in <tex> 

### ISSUE THREAD

**Issue by abhinavc** [adamarla/qQuill#19]
Quill allows only the isImage attribute to be set in <tex> 
But I need to add a new isTex (or tex) attribute now. 

Hence, either allow for isTex="true | false" or disable all checks for now 

This is an urgent requirement.

**Comment by abhinavc** [comment]
Needless to say, layout.xml should reflect any and all attributes set in source.xml

**Comment by adamarla** [comment]
I can edit the code to print isTex="true" for for all tex elements which are not prefab svgs if that is what you want me to do. Or I can edit the code to set isImage="false" for the same. Let me know what you want me to do.

I am due to take a flight from Boston to Nashville today though so I'll do it only in the evening (US time).

**Comment by adamarla** [comment]
I can formalize this change as part of quill -r? It will be more reliable than sed based text replacement in the xml file. 
If so, tell me precisely what the attribute needs to be - isTex="true" for tex elements that are backed by LaTeX or something else?
